#!/usr/bin/env bash

# Install homebrew if not already installed
if [ ! -x "$(command -v brew)" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew update && brew upgrade

packages=(
  bat
  coreutils
  eza
  ffmpeg
  fzf
  git
  git-lfs
  git-delta
  golang
  jordanbaird-ice
  htop
  mosh
  nmap
  nvm
  neovim
  pyenv
  ripgrep
  stow
  thefuck
  tig
  tldr
  tree
  yt-dlp
)
brew install "${packages[@]}"

fonts=(
  font-cascadia-code
  font-hack-nerd-font
  font-jetbrains-mono
  font-jetbrains-mono-nerd-font
)
brew install "${fonts[@]}"

apps=(
  appcleaner
  betterdisplay
  font-jetbrains-mono
  ghostty
  maccy
  netnewswire
  scroll-reverser
  spotmenu
  vlc
)
brew install --cask "${apps[@]}"

# Cleanup
brew cleanup
