#!/usr/bin/env bash

# Install homebrew if not already installed
if [[ ! -x "$(command -v brew)" ]]; then
  xcode-select --install
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew update
brew upgrade

# Install brew packages
packages=(
  coreutils
  bat
  diff-so-fancy
  fd
  git
  git-lfs
  httpie
  jq
  golang
  gotop
  nmap
  nvm
  neovim
  pure
  pyenv
  ripgrep
  shellcheck
  stow
  tig
  tldr
  thefuck
  tree
  vim
  z
)

brew install "${packages[@]}"

# Install fonts
fonts=(
  font-fira-code
  font-cascadia-code
  font-hack-nerd-font
)

brew tap homebrew/cask-fonts
brew install --cask "${fonts[@]}"

# Cleanup
brew cleanup
