#!/usr/bin/env bash

# == Finder ==
# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# Show hidden files
defaults write com.apple.finder AppleShowAllFiles true # show hidden files
# Show path bar
defaults write com.apple.finder ShowPathbar -bool true
# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# Disable warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false
# Disable warning when renaming file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# == Dock ==
# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true
# Set the icon size of Dock items
defaults write com.apple.dock tilesize -int 42
# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false
# Faster dock animation
defaults write com.apple.dock expose-animation-duration -float 0.1

# == Hot corners & Spaces ==
# Lock screen top-left+cmd
defaults write com.apple.dock wvous-bl-corner -int 12
defaults write com.apple.dock wvous-bl-modifier -int 1048576
# Disable: Auto Reorder Spaces based on most recent use
defaults write com.apple.dock "mru-spaces" -bool "false"

# == Mouse/trackpack/bluetooth ==
# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
# Faster mouse scroll speed
defaults write com.apple.scrollwheel.scaling -float 0.7
# Faster key repeat
defaults write InitialKeyRepeat -int 10
defaults write KeyRepeat -int 1
# Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# == Typing ==
# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
# Disable smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
# Disable automatic capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
# Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# == Screenshots ==
# Disable shadow
defaults write com.apple.screencapture "disable-shadow" -bool true

# == Apply changes ==
killall Dock &>/dev/null
killall Finder &>/dev/null
