#!/usr/bin/env bash

# Link dotfiles
rm -rf ~/.config/nvim
stow nvim

# Install vim-plug for neovim
[[ -f ~/.config/nvim/autoload/plug.vim ]] ||
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins
nvim +'PlugInstall --sync' +qa