#!/usr/bin/env bash

python_version="3.10"

# Fetch latest stable version
latest="$(curl -s https://endoflife.date/api/python.json | jq -r '.[0].cycle')"
if [ -n "$latest" ]; then
  python_version="$latest"
fi

# Create directory
mkdir -p ~/.pyenv

# Install specific python version globally
if [ -z "$(pyenv versions | grep "$python_version" | tail -1)" ]; then
  echo "Installing Python v$python_version..."
  pyenv install "$python_version"":latest"
  pyenv global "$(pyenv versions | grep "$python_version")"
else
  echo "Python v$python_version is already installed."
fi
